name: Prueba de Merge Queue

on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
    branches:
        - 'master'


jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar prueba de Merge Queue
        run: |
          cd $GITHUB_WORKSPACE
          bash test-mq-2.sh $GITHUB_WORKSPACE/archivo-prueba.txt

      - name: Verificar resultado
        if: ${{ failure() }}
        run: exit 1
