name: Prueba de Merge Queue

on:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
    branches:
        - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar prueba
        run: |
          cd $GITHUB_WORKSPACE
          bash test-mq-2.sh $GITHUB_WORKSPACE/archivo-prueba.txt

      - name: Verificar resultado
        if: ${{ failure() }}
        run: exit 1

      - name: Fast Forward PR
        uses: ./.github/workflows/ffpr.yml
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

