name: Prueba de Merge Queue

on:
  # merge_group:
  #   types: [checks_requested]
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
    branches:
        - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar prueba de Merge Queue
        run: |
          cd $GITHUB_WORKSPACE
          bash test-mq-2.sh $GITHUB_WORKSPACE/archivo-prueba.txt

      - name: Verificar resultado
        if: ${{ failure() }}
        run: exit 1

  ff-merge:
    needs: [ prueba ]
    runs-on: ubuntu-latest
    steps:
     - name: Fast-Forward PR
       uses: endre-spotlab/fast-forward-js-action@2.1
       with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          production_branch: 'master'
          staging_branch: 'staging'
